config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  root 'toppages#index'
  
  resources :items do 
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  
  resources :categories, only: [:index, :show, :new, :edit, :destroy]
  resources :home 

  resources :users
  #   collection do
  #     delete 'user_delete', to: 'users#destroy' 
  #   end
  # end


  resources :buyers, only: [:index, :show, :edit, :update] do
    member do
      post 'pay', to: 'buyers#pay'
      get 'done', to: 'buyers#done'
    end
  end
  
  resources :card, only: [:new, :show] do
    collection do
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :validatable, password_length: 7..128

         has_many :items
         has_many :cards
         has_many :addresses
         accepts_nested_attributes_for :addresses, allow_destroy: true

         validates :nick_name,              presence: true, length: {maximum: 20}
         validates :email,                 presence: true, uniqueness: { case_sensitive: false }
         validates :family_name,           presence: true, length: {maximum: 35}
         validates :first_name,             presence: true, length: {maximum: 35}
         validates :family_name_kana,      presence: true, length: {maximum: 35}
         validates :first_name_kana,       presence: true, length: {maximum: 35}

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
    @user.addresses.new
  end

  # POST /resource
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end


  def edit
    @user = User.find_by(id: current_user.id)

  end

  def update
    if current_user.update(user_params)
      sign_in(current_user, bypass: true)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:nick_name, :family_name, :first_name, :family_name_kana, :first_name_kana, :email, :birthday, :password, addresses_attributes: [:postal_code, :municipalities, :address, :home_type, :tel, :id])
  end

  # GET /resource/edit


  # PUT /resource


  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # # POST /resource/sign_in
  # def create
  #   @user = User.find(params[:id])
  #   if @user.save
  #     redirect_to root_path
  #   else
  #     render :new
  #   end


  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include CommonActions
  before_action :get_categories, only:[:index, :destroy, :show]

  def create
  end

  def new
  end

  def index
    @item = Item.all.order("RAND()").limit(9).where.not(seller_id: current_user.id).where(buyer_id: nil)
    @user = current_user.nick_name
  end

  def destroy
  end

  def show
    @item = Item.all.order("id DESC").limit(9).where(seller_id: current_user.id).where(buyer_id: nil)
  end

  
  private
  def user_params
    params.require(:user).permit(:nick_name, :family_name, :first_name, :family_name_kana, :first_name_kana, :birthday)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_side_user.html.haml
.left_user
  .left_user__action
    %h.tag ユーザー情報
    .list 
      %il 
        = link_to '出品する', '/items/new'
        %ul
          %li
            .fas.fa-chevron-right
    .list
      %il 
        = link_to '出品中', '/users/show'
        %ul
          %li
            .fas.fa-chevron-right
    .list
      %il 
        = link_to '出品履歴', '/items', method: :get
        %ul
          %li
            .fas.fa-chevron-right
    .list
      %il 
        = link_to '購入履歴', '/buyers'
        %ul
          %li
            .fas.fa-chevron-right
  .left_user__configration
    %h.tag ユーザー設定
    .list
      %il 
        = link_to 'プロフィール(ユーザー編集)', 'users/edit'
        %ul
          %li
            .fas.fa-chevron-right
    .list
      %il 
        =link_to 'クレジット情報', delete_card_index_path
        %ul
          %li
            .fas.fa-chevron-right
    .list
      %il 
        =link_to 'クレジット登録', new_card_path, data: {"turbolinks" => false}
        %ul
          %li
            .fas.fa-chevron-right

app/views/users/_user_mypage.html.haml
.wapper
  = render 'toppages/toppage_header'
  .user_main_contents
    = render 'side_user'
    .right_user
      .user_top 商品一覧
      .side_tab
        .tab_contents
          - @item.each do |i|
            %ul
              %li
                = link_to item_path(i.id) do
                  = image_tag i.images[0].image.url, class: "pro_pic"
              %li.pro_name
                = i.name
  .footer
  = render 'toppages/toppage_footer'

app/views/users/destroy.html.haml
//ログアウト
.wapper
  = link_to new_item_path do
    .exhibitionIcon
      .exhibitionIcon__text
        出品する
      .fas.fa-camera.fa-6x
  = render 'toppages/toppage_header'
  .logout_main_content
    = render 'side_user'
    .right_log.out 
      .log_out.content
        = link_to "Logout", destroy_user_session_path, method: :delete, class: "log_out.button"
  = render 'toppages/toppage_footer'

app/views/users/index.html.haml
.wapper
  = link_to new_item_path do
    .exhibitionIcon
      .exhibitionIcon__text
        出品する
      .fas.fa-camera.fa-6x
  = render "users/user_mypage"

app/views/users/show.html.haml
//出品ページ
.wapper
  = render 'toppages/toppage_header'
  = link_to new_item_path do
    .exhibitionIcon
      .exhibitionIcon__text
        出品する
      .fas.fa-camera.fa-6x
  .user_main_contents
    = render 'side_user'
    .right_user
      .user_top 出品中
      .side_tab
        .tab_contents
          - @item.each do |i|
            %ul
              %li
                = link_to item_path(i.id) do
                  = image_tag i.images[0].image.url, class: "pro_pic"
              %li.pro_name
                = i.name
  .footer
  = render 'toppages/toppage_footer'

app/views/users/user_logout.html.haml
.wapper
  .header_logout
  .logout_main_content
    = render 'side_user'
    .right_log.out 
      .log_out.content 
        .log_out.button LogOut