config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  root 'toppages#index'
  
  resources :items do 
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  
  resources :categories, only: [:index, :show, :new, :edit, :destroy]
  resources :home 

  resources :users
  #   collection do
  #     delete 'user_delete', to: 'users#destroy' 
  #   end
  # end


  resources :buyers, only: [:index, :show, :edit, :update] do
    member do
      post 'pay', to: 'buyers#pay'
      get 'done', to: 'buyers#done'
    end
  end
  
  resources :card, only: [:new, :show] do
    collection do
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end


end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  
  validates :customer_id,             presence: true
  validates :card_id,                 presence: true
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"
  before_action :set_card, only: [:show, :delete]

  def new
    @card = Card.new
    @category = Category.all.order("id ASC").limit(13)
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to '/users', notice: "削除しました"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    if @card.blank?
      redirect_to action: "new"
    end
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
      redirect_to action: "new"
  end
  
  def show
    if @card.blank?
      redirect_to users_path
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  private

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/card/new.html.haml
.wapper
  = render 'toppages/toppage_header'
= form_tag(pay_card_index_path, method: :post, name: "inputForm") do
  .form-card
    .form-card__content
      .c-num.cc
        .c-num__title
          カード情報を入力して下さい
        %br
        .c-num__top
          .label カード番号
          .label-mark 必須
        .c-num__bottom
          = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
        .c-num__icons
          .c-num__icon
            .fab.fa-cc-jcb
          .c-num__icon
            .fab.fa-cc-amex
          .c-num__icon
            .fab.fa-cc-visa
          .c-num__icon
            .fab.fa-cc-mastercard
          .c-num__icon
            .fab.fa-cc-diners-club
          .c-num__icon
            .fab.fa-cc-discover
        .c-date__top
          .label 有効期限
          .label-mark 必須
        .c-date__bottom
          .c-date__bottom__left
            %select#exp_month{name: "exp_month", type: "text"}
              %option{value: ""} --
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            %span 月
          .c-date__bottom__right            
            %select#exp_year{name: "exp_year", type: "text"}
              %option{value: ""} --
              %option{value: "2019"}19
              %option{value: "2020"}20
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
            %span 年
      .c-num.cc
        .c-num__top
          .label セキュリティコード
          .label-mark 必須
        .c-num__bottom
        = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
      .c-submit.ss
        #card_token
        = submit_tag "追加する", id: "token_submit"
.wapper
  = render 'toppages/toppage_footer'

app/views/card/show.html.haml
.show__card--main
  .show__card--main--body
    %label.show__cards__title 支払い一覧
    .show__card--body
      .show__card--body__tab
        .show__card--body__tab__list
          .show__card--body__tab__list__title クレジットカード一覧
          .show__card--body__tab__list__body
            = icon 'fab', 'cc-visa', class:'show__card--body__tab__list__body--icon'
            %br.show__card--body__tab__list__body__main
              = "**** **** **** " + @default_card_information.last4
            %br.show__card--body__tab__list__body__card
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year
              = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
                %input{ type: "hidden", name: "card_id", value: "" }
                %button.show__card__delete 削除する
      .show__card--body__bottom 
        = link_to "#", class:"show__card--body__bottom__link" do
          支払い方法について
          = icon 'fas', 'chevron-right', class:'list--icon'