config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  root 'toppages#index'
  
  resources :items do 
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  
  resources :categories, only: [:index, :show, :new, :edit, :destroy]
  resources :home 

  resources :users
  #   collection do
  #     delete 'user_delete', to: 'users#destroy' 
  #   end
  # end


  resources :buyers, only: [:index, :show, :edit, :update] do
    member do
      post 'pay', to: 'buyers#pay'
      get 'done', to: 'buyers#done'
    end
  end
  
  resources :card, only: [:new, :show] do
    collection do
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end


end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  include CommonActions
  before_action :get_categories, only:[:index, :update]

  require 'payjp'
  before_action :set_card, only: [:show, :pay]
  before_action :set_item, only: [:show, :pay]

  def show
    if @item.seller_id == current_user.id || @item.buyer_id != nil
      redirect_to root_path
    elsif @card.blank?
      redirect_to controller: "card", action: :new
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def pay
    redirect_to root_path if @item.seller_id == current_user.id || @item.buyer_id != nil
      @item.update(buyer_id: current_user.id)
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      Payjp::Charge.create(
        :amount => @item.price,
        :customer => @card.customer_id,
        :currency => 'jpy',
      )
      redirect_to root_path #tトップページに遷移
  end

  def index
    @item = Item.all.where(buyer_id: current_user.id)
  end

  def edit
  end
  
  def update
  end

  private

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/views/buyers/done.html.haml
%h2 購入が完了しました

app/views/buyers/index.html.haml
.wapper
  = link_to new_item_path do
    .exhibitionIcon
      .exhibitionIcon__text
        出品する
      .fas.fa-camera.fa-6x
  = render 'toppages/toppage_header'
  .user_main_contents
    = render 'users/side_user'
    .right_user
      .user_top 購入一覧
      .side_tab
        .tab_contents
          - @item.each do |i|
            %ul
              %li
                = link_to item_path(i.id) do
                  = image_tag i.images[0].image.url, class: "pro_pic"
              %li.pro_name
                = i.name
  .footer
  = render 'toppages/toppage_footer'

app/views/buyers/show.html.haml
.exhibitionHeader
  = link_to root_path do
    = image_tag "logo.png", alt: "furima icon", id: "pic1", class: "exhibitionHeader__logo"
.main-content
  %main.pay-main
    %section.pay-item-content
      %h2.pay-head 購入内容確認
      %section.pay-item
        .pay-content-info
          - @item.images.each_with_index do |item, i|
            - if i == 0
              = image_tag item.image.url, class: "itemImage", class: "pay-item__image"

          .pay-content-info__text
            %p.pay-price 
              = number_to_currency(@item.price, unit: "￥",precision: 0)
              %span.mop
                = @item.postage.name
           
      %section.pay-user-info
        .pay-content-info
          %h3.deli お届け先
          %address.user-info
            - current_user.addresses.each do |address|
              .user-info--text
                〒
                = address.postal_code
              .user-info--text
                = address.municipalities
                = address.address
              .user-info--text
                = address.home_type
              .user-info--text
                TEL
                = address.tel

      %section.pay-user-info
        .pay-content-info
          %h3.deli クレジット
          - if @default_card_information.blank?
            %br /
          - else
            = "**** **** **** " + @default_card_information.last4
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
            = form_tag(pay_buyer_path(@item), method: :post) do
              %button.buybotn 購入する